name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      - name: .NET build
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet pack -c Release

      - name: .NET test
        run: |
          dotnet test
